aggregate: Cart
apigateway: minos
apigateway_deploy: self-hosted
author: Clariteia Devs
broker: kafka
broker_deploy: self-hosted
database: postgres
deploy: docker-compose
description: This is the cart of our Online Boutique
discovery: minos
discovery_database: redis
discovery_deploy: self-hosted
email: devs@clariteia.com
language: python
name: cart
package_manager: poetry
postgres_deploy: self-hosted
project_deploy: docker-compose
project_description: This is an Online Boutique with Minos Microservices
project_name: eboutique
project_version: 0.1.0
redis_deploy: self-hosted
template_name: project-init
template_registry: https://github.com/minos-framework/minos-templates/releases/download/v0.1.0
template_version: v0.1.0
version: 0.1.0
