from collections.abc import (
    Awaitable,
    Callable,
)
from typing import (
    Optional,
)
from uuid import (
    UUID,
)

from minos.aggregate import (
    TransactionEntry,
)
from minos.networks import (
    REQUEST_HEADERS_CONTEXT_VAR,
    BrokerRequest,
    Request,
    Response,
)


async def transactional_command(
    request: Request, inner: Callable[[Request], Awaitable[Optional[Response]]]
) -> Optional[Response]:
    """Execute the command transactionally if it comes from a saga.

    :param request: The request containing the data.
    :param inner: The inner handling function to be executed.
    :return: The response generated by the inner handling function.
    """
    try:
        if isinstance(request, BrokerRequest):
            message = request.raw
            raw_transaction_uuids = message.headers.get("transactions", None)
            if raw_transaction_uuids:
                transaction_uuids = list(map(UUID, raw_transaction_uuids.split(",")))
                return await _transaction(request, inner, transaction_uuids)
        return await inner(request)
    finally:
        headers = REQUEST_HEADERS_CONTEXT_VAR.get()
        if headers is not None:
            headers["transactions"] = f",{headers.get('transactions')}".rsplit(",", 1)[0]


async def _transaction(
    request: Request, inner: Callable[[Request], Awaitable[Optional[Response]]], transaction_uuids: list[UUID]
) -> Optional[Response]:
    if len(transaction_uuids):
        async with TransactionEntry(uuid=transaction_uuids[0], autocommit=False):
            return await _transaction(request, inner, transaction_uuids[1:])

    return await inner(request)
