---
- hosts: localhost
  connection: local
  tasks:
    - name: Check Syntax
      shell: poetry run flake8
      args:
        chdir: ../
      register: results

    - debug: var=results.stdout_lines

    - debug: var=results.stderr_lines
