---
- hosts: localhost
  connection: local
  tasks:
    - name: Test package
      shell: poetry install
      args:
        chdir: ../
      register: results

    - debug: var=results.stdout_lines

    - debug: var=results.stderr_lines
