[tool.poetry]
name = "minos-microservice-aggregate"
version = "0.8.0.dev3"
description = "The Aggregate pattern of the Minos Framework"
readme = "README.md"
repository = "https://github.com/minos-framework/minos-python"
homepage = "https://www.minos.run"
authors = ["Minos Framework Devs <hey@minos.run>"]
license = "MIT"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
]
keywords = [
    "clariteia",
    "minos",
    "microservice",
    "saga",
]
packages = [
    { include = "minos" },
]
include = [
    { path = "AUTHORS.md", format = "sdist" },
    { path = "HISTORY.md", format = "sdist" },
    { path = "LICENSE", format = "sdist" },
]

[tool.poetry.dependencies]
python = "^3.9"
minos-microservice-common = "^0.8.0.dev"
minos-microservice-networks = "^0.8.0.dev"
minos-microservice-transactions = "^0.8.0.dev"
minos-microservice-saga = "^0.8.0.dev"
cached-property = "^1.5.2"

[tool.poetry.dev-dependencies]
minos-microservice-common = { path = "../minos-microservice-common", develop = true }
minos-microservice-networks = { path = "../minos-microservice-networks", develop = true }
minos-microservice-transactions = { path = "../minos-microservice-transactions", develop = true }
minos-microservice-saga = { path = "../minos-microservice-saga", develop = true }
black = "^22.3"
isort = "^5.8.0"
pytest = "^7.1.2"
coverage = "^6.4"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
