[tool.poetry]
name = "minos-microservice-cqrs"
version = "0.2.1"
description = "Minos Microservice CQRS package"
readme = "README.md"
repository = "https://github.com/minos-framework/minos-python"
homepage = "http://www.minos.run/"
authors = ["Clariteia Devs <devs@clariteia.com>"]
license = "MIT"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
]
keywords = [
    "clariteia",
    "minos",
    "microservice",
    "saga",
]
packages = [
    { include = "minos" }
]
include = [
    "AUTHORS.md",
    "HISTORY.md",
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.9"
dependency-injector = "^4.34.0"
minos-microservice-common = "^0.3.0"
minos-microservice-networks = "^0.3.0"
minos-microservice-aggregate = "^0.2.2"

[tool.poetry.dev-dependencies]
minos-microservice-common = { path = "../minos-microservice-common", develop = true }
minos-microservice-networks = { path = "../minos-microservice-networks", develop = true }
minos-microservice-aggregate = { path = "../minos-microservice-aggregate", develop = true }
black = "^21.12b0"
isort = "^5.8.0"
pytest = "^6.2.4"
coverage = "^6.3"
flake8 = "^4.0.1"
Sphinx = "^4.0.1"
pre-commit = "^2.12.1"
sphinx-autodoc-typehints = "^1.12.0"
sphinxcontrib-apidoc = "^0.3.0"
sphinx-rtd-theme = "^1.0.0"
m2r2 = "^0.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
