name: "Test: minos-microservice-transactions"

on:
  push:
    branches:
      - main
      - '*.*.x'
  pull_request:
    paths:
      - 'packages/core/minos-microservice-transactions/**'
      - 'packages/core/minos-microservice-networks/**'
      - 'packages/core/minos-microservice-common/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-buster
    defaults:
      run:
        working-directory: packages/core/minos-microservice-transactions

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: make install

      - name: Lint package
        run: make lint

      - name: Test package with coverage
        run: make coverage

      - name: Publish coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/core/minos-microservice-transactions/coverage.xml
          fail_ci_if_error: true

      - name: Generate documentation
        run: make docs

      - name: Generate build
        run: make dist
