name: "Test: minos-database-aiopg"

on:
  push:
    branches:
      - main
      - '*.*.x'
  pull_request:
    paths:
      - 'packages/plugins/minos-database-aiopg/**'
      - 'packages/core/minos-microservice-aggregate/**'
      - 'packages/core/minos-microservice-networks/**'
      - 'packages/core/minos-microservice-common/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-buster
    defaults:
      run:
        working-directory: packages/plugins/minos-database-aiopg

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: minos
          POSTGRES_PASSWORD: min0s
          POSTGRES_DB: order_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      MINOS_DATABASES_DEFAULT_HOST: postgres

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: make install

      - name: Lint package
        run: make lint

      - name: Test package with coverage
        run: make coverage

      - name: Publish coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/plugins/minos-database-aiopg/coverage.xml
          fail_ci_if_error: true

      - name: Generate documentation
        run: make docs

      - name: Generate build
        run: make dist
